env:
 global:
  - OUT_NAME=$PROJ_NAME-$TRAVIS_BRANCH.zip
language: CSharp
mono:
  - latest
before_install:
 - sudo add-apt-repository ppa:lyx-devel/release -y
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
 - sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
 - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
 - sudo apt-get -qq update
 - sudo apt-get -qq install lyx
 - sudo apt-get install -qq texlive-fonts-extra
 - sudo apt-get install -qq texlive-lang-polish
 - sudo apt-get install dotnet=1.0.0.001598-1
 - mkdir ~/.lyx
 - mkdir ~/.lyx/layouts
 - cp ./Docs/Thesis/src/dcsbook.cls ~/.lyx/layouts/dcsbook.cls
 - cp ./Docs/Thesis/src/dcslib.sty ~/.lyx/layouts/dcslib.sty
 - cp ./Docs/Thesis/src/dcsbook.layout ~/.lyx/layouts/dcsbook.layout
install:
 - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
 - dnvm upgrade
 - dnu restore
script:
 - mkdir out
 - lyx -batch --export-to pdflatex ./out/MasterThesis.pdf ./Docs/Thesis/src/RestTestingFramework.lyx 
 - ls -la ./out
 - dnx -p ./Soft/MasterThesis.RestTestsGenerator.Tests/project.json test
 - dnu publish .\Soft\MasterThesis.RestTestsGenerator\project.json -o .\Out\soft
after_success:
 - zip -r -j $OUT_NAME out/*
 - ls -la
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: $OUT_NAME
  skip_cleanup: true
  on:
    tags: true