env:
 global:
  - OUT_NAME=$MAJOR.$TRAVIS_BUILD_NUMBER.$TRAVIS_COMMIT.zip
before_install:
 - sudo add-apt-repository ppa:lyx-devel/release -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq lyx
 - sudo apt-get install -qq texlive-fonts-extra
 - sudo apt-get install -qq texlive-lang-polish

script:
 - mkdir out
 - lyx -batch --export-to pdf2 ../../out/MasterThesis.pdf ./Docs/Thesis/src/RestTestingFramework.lyx 
 - ls -la ./out
after_success:
 - zip -r $OUT_NAME out
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: $OUT_NAME
  skip_cleanup: true
  on:
    tags: true