env:
 global:
  - OUT_NAME=$PROJ_NAME-$TRAVIS_BRANCH.zip
before_install:
 - sudo apt-get dist-upgrade
 - sudo add-apt-repository ppa:lyx-devel/daily -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq lyx
 - sudo apt-get install -qq texlive-full
 - mkdir ~/texmf
 - mkdir ~/texmf/tex
 - mkdir ~/texmf/tex/latex
 - cp ./Docs/Thesis/src/dcsbook.cls ~/texmf/tex/latex/dcsbook.cls
 - cp ./Docs/Thesis/src/dcslib.sty ~/texmf/tex/latex/dcslib.sty
 - cp ./Docs/Thesis/src/dcsbook.layout ~/texmf/tex/latex/dcsbook.layout
 - lyx -version
script:
 - mkdir out
 - lyx -batch --export-to pdf2 ./out/MasterThesis.pdf ./Docs/Thesis/src/RestTestingFramework.lyx 
 - ls -la ./out
after_success:
 - zip -r -j $OUT_NAME out/*
 - ls -la
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: $OUT_NAME
  skip_cleanup: true
  on:
    tags: true